Region Picker Selection based on SessionStorage
adobe/theblog pull request #582
Opened 2021-01-28 15:15 UTC by elaineskpt

Enhancements for https://github.com/adobe/theblog/issues/419

The actual footer in blogs do not have the region picker button, so I used the acom experience for the test.
Created already a story is to author the footer for blogs based on the XD.   https://jira.corp.adobe.com/browse/MWPW-81134

2021-01-29 07:20 UTC, rofe requested changes
I would use `localStorage`, not `sessionStorage`. A visitior's language preference likely doesn't change every time with every browser session.

2021-01-29 09:25 UTC, kptdobe commented
@rofe In the current stage, I do not agree.
A surfer arriving on `/` is on the EN site. With the `localStorage` persistence, he would be displayed as being on `uk` or `apac` if he selected once this region. This is not correct.
We do not want to implement a complex machinery to track regions (something like if a surfer selected `uk` once, his `/` redirects to `/en/uk.html`), the only purpose of storing the region in the `sessionStorage` is to be able to show the selected region when he surfs on the articles after passing by the landing page. Nothing more. Next time he comes to the site, this is all reset. If he bookmarks `/en/uk.html`, then the `sessionStorage` will always be set.

2021-02-01 14:46 UTC, elaineskpt commented
I'll be merging this one to the Branch as we decided to go with `sessionStorage` for the moment

2021-02-01 14:46 UTC, merged

2021-02-01 15:07 UTC, kptdobe commented
Why do you merge while there are multiple feedback that have not been addressed ? You merged some code which does not make any sense (https://github.com/adobe/theblog/blob/region-picker/scripts.js#L273)

2021-02-01 15:14 UTC, elaineskpt commented
oh wait let me take a look, if there was my latest changes @kptdobe

2021-02-01 16:35 UTC, elaineskpt commented
Hi @kptdobe latest changes were added to the https://github.com/adobe/theblog/pull/585